baseURL = 'https://vonyuan.github.io/'
languageCode = 'en-us'
title = 'Dev Ops Wannabe'
theme ='paper'

[params]
github = 'VonYuan'
linkedin = 'voonyuan'

avatar = 'xkalle101@gmail.com'
name = 'Voon Yuan'
bio = 'Recent Fresh Graduate'


monoDarkIcon = true